package com.xu.mybatis_ssm.bean;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Sat Oct 13 21:57:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept
     *
     * @mbg.generated Sat Oct 13 21:57:50 CST 2018
     */
    private String dept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Sat Oct 13 21:57:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Sat Oct 13 21:57:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept
     *
     * @return the value of department.dept
     *
     * @mbg.generated Sat Oct 13 21:57:50 CST 2018
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept
     *
     * @param dept the value for department.dept
     *
     * @mbg.generated Sat Oct 13 21:57:50 CST 2018
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }
}